### ISSUE TITLE
Rust bindings needs Pkg config on windows 11?

### ISSUE THREAD

**Issue by thebest132** [dankamongmen/libnotcurses-sys#36] opened 2024-10-10 20:01 UTC
Opened an issue in the high level Notcurses repository in rust but no response. I'm trying to use notcurses in my library but making every user of my library download pkg config to use my rust library sucks. How do I even download pkg config easily? There's nothing in the README about it.

Edit: just did the installation process from INSTALL.md and it did nothing. What

**Comment by joseluis** [comment] 2024-10-14 20:46
duplicate of #35

**Closed as completed by joseluis** 2024-10-14 20:46 UTC
Labels: duplicate
